---
title: "Divorce Rate in Different States and Years"
author: "Xiang Cheng, Benny Chen, Sena"
date: "11/15/2022"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r,  echo = FALSE}
# Summary Calculations
source("../source/Calculation_Summary.R")
# number of states: num_state
# number of years: num_year
# year of minimum divorce rate: min_year
# year of maximum divorce rate: max_year
# minimum divorce rate: min_rate
# maximum divorce rate: max_rate
# mean of divorce rate: mean_rate
# state has the highest divorce rate: max_rate_record
# standard deviation of divorce rate: sd_divorce_rate
```

```{r}
#### Dynamic paragraph:
msg <- "We calculated and created the different values by analyzing and summarizing the rate data in different years and displayed it to the audience in the form of data visualization. This way, the audience can intuitively see the increasing or decreasing trend of the divorce rate each year. First, we used min_year and max_year to determine the start and the end of this data set. Second, we emplyed min_rate and max_rate to realize the range of divorce rate in recent years. Third, we calculated value of mean_rate to estimate the average divorce rate. Fourth, we found the max_rate_record, which was the state that had the most divorce rate. Finally, we calulated the standard deviation of divorce rate in recent 10 years finding divorce rates were clustered and relatively stable."
```

```{r, echo = FALSE}
####Table:
source("../source/Table Summary.R")
```

```{r, echo = FALSE}
#### Chart(Divorce Rate Over Time)
source("../source/Chart1.R")
msg < -"This chart represents divorce rate over 30 years.
***X-axis*** is the year and ***Y  -axis*** is the divorce rate."
```

```{r, echo = FALSE}
#### Chart(Comparison of Divorce Rate in Washington and New Jersey)
source("../source/Chart2.R")
msg < -"We chose two states to represent the East and West, and this plot shows the change in divorce rates over 30 years in Washington (West) and New Jersey (East).
***X-axis*** is the year and ***Y  -axis*** is the divorce rate."
```

```{r, echo = FALSE}
#### Chart(Divorce Rate in 2020)
source("../source/Chart3.R")
msg < -"This chart demonstrates to Ten States With Highest Divorce Rate in 2020.
***X-axis*** is the divorce rate and ***Y  -axis*** is the state."
```

